version: "3"

services:
  server:
    build:
      context: ./source
      dockerfile: Dockerfile
    volumes:
      - ./source/:/source/
    command: uvicorn app.api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./source/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./source/.env
    ports:
      - 5432:5432

volumes:
  postgres_data:
